NDK_TOOLCHAIN_VERSION=clang
APP_CPPFLAGS += -std=c++14
APP_STL := c++_static
APP_PLATFORM := android-16
APP_ABI=armeabi-v7a
APP_MODULES= libavcodec libjniopencv_xfeatures2d libavdevice libjniopencv_ximgproc libavfilter libjnipostproc libavformat libjniswresample libavutil libjniswscale libjniavcodec libopencv_calib3d libjniavdevice libopencv_core libjniavfilter libopencv_dnn libjniavformat libopencv_face libjniavutil libopencv_features2d libjnicvkernels libopencv_flann libjniopencv_calib3d libopencv_highgui libjniopencv_core libopencv_imgcodecs libjniopencv_dnn libopencv_imgproc libjniopencv_face libopencv_ml libjniopencv_features2d libopencv_objdetect libjniopencv_flann libopencv_optflow libjniopencv_highgui libopencv_photo libjniopencv_imgcodecs libopencv_shape libjniopencv_imgproc libopencv_stitching libjniopencv_ml libopencv_superres libjniopencv_objdetect libopencv_video libjniopencv_optflow libopencv_videoio libjniopencv_photo libopencv_videostab libjniopencv_shape libopencv_xfeatures2d libjniopencv_stitching libopencv_ximgproc libjniopencv_superres libpostproc libjniopencv_video libswresample libjniopencv_videoio libswscale libjniopencv_videostab elisa

