/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uiuc_bioassay_elisa_ELISAApplication */

#ifndef _Included_uiuc_bioassay_elisa_ELISAApplication
#define _Included_uiuc_bioassay_elisa_ELISAApplication
#ifdef __cplusplus
extern "C" {
#endif
#undef uiuc_bioassay_elisa_ELISAApplication_RED_LASER_NM
#define uiuc_bioassay_elisa_ELISAApplication_RED_LASER_NM 656.26
#undef uiuc_bioassay_elisa_ELISAApplication_GREEN_LASER_NM
#define uiuc_bioassay_elisa_ELISAApplication_GREEN_LASER_NM 532.1
#undef uiuc_bioassay_elisa_ELISAApplication_MAX_PICTURE
#define uiuc_bioassay_elisa_ELISAApplication_MAX_PICTURE 8L
/*
 * Class:     uiuc_bioassay_elisa_ELISAApplication
 * Method:    cleanFolder
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_uiuc_bioassay_elisa_ELISAApplication_cleanFolder
  (JNIEnv *, jclass, jstring);

/*
 * Class:     uiuc_bioassay_elisa_ELISAApplication
 * Method:    processBB
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_uiuc_bioassay_elisa_ELISAApplication_processBB
  (JNIEnv *, jclass, jstring);

/*
 * Class:     uiuc_bioassay_elisa_ELISAApplication
 * Method:    processSample
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_uiuc_bioassay_elisa_ELISAApplication_processSample
  (JNIEnv *, jclass, jstring);

/*
 * Class:     uiuc_bioassay_elisa_ELISAApplication
 * Method:    readRGBSpec
 * Signature: (Ljava/lang/String;)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_uiuc_bioassay_elisa_ELISAApplication_readRGBSpec
  (JNIEnv *, jclass, jstring);

/*
 * Class:     uiuc_bioassay_elisa_ELISAApplication
 * Method:    readBBResNormalized
 * Signature: (Ljava/lang/String;)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_uiuc_bioassay_elisa_ELISAApplication_readBBResNormalized
  (JNIEnv *, jclass, jstring);

/*
 * Class:     uiuc_bioassay_elisa_ELISAApplication
 * Method:    readSampleResNormalized
 * Signature: (Ljava/lang/String;)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_uiuc_bioassay_elisa_ELISAApplication_readSampleResNormalized
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
