/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uiuc_bioassay_elisa_ELISAApplication */

#ifndef _Included_uiuc_bioassay_elisa_ELISAApplication
#define _Included_uiuc_bioassay_elisa_ELISAApplication
#ifdef __cplusplus
extern "C" {
#endif
#undef uiuc_bioassay_elisa_ELISAApplication_RED_LASER_NM
#define uiuc_bioassay_elisa_ELISAApplication_RED_LASER_NM 656.26
#undef uiuc_bioassay_elisa_ELISAApplication_GREEN_LASER_NM
#define uiuc_bioassay_elisa_ELISAApplication_GREEN_LASER_NM 532.1
#undef uiuc_bioassay_elisa_ELISAApplication_MAX_PICTURE
#define uiuc_bioassay_elisa_ELISAApplication_MAX_PICTURE 8L
/*
 * Class:     uiuc_bioassay_elisa_ELISAApplication
 * Method:    cleanFolder
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_uiuc_bioassay_elisa_ELISAApplication_cleanFolder
  (JNIEnv *, jclass, jstring);

/*
 * Class:     uiuc_bioassay_elisa_ELISAApplication
 * Method:    processBBELISA
 * Signature: (Ljava/lang/String;)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_uiuc_bioassay_elisa_ELISAApplication_processBBELISA
  (JNIEnv *, jclass, jstring);

/*
 * Class:     uiuc_bioassay_elisa_ELISAApplication
 * Method:    processSampleELISA
 * Signature: (Ljava/lang/String;)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_uiuc_bioassay_elisa_ELISAApplication_processSampleELISA
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
